/* Generated By:JavaCC: Do not edit this line. JASONConstants.java */
package testJJ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JASONConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int COMMENT_INNER = 7;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 8;
  /** RegularExpression Id. */
  int COMMENT_CORE = 9;
  /** RegularExpression Id. */
  int ARRAY = 10;
  /** RegularExpression Id. */
  int BEGIN = 11;
  /** RegularExpression Id. */
  int CALL = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int ENDIF = 16;
  /** RegularExpression Id. */
  int ENDUNTIL = 17;
  /** RegularExpression Id. */
  int ENDWHILE = 18;
  /** RegularExpression Id. */
  int FUNCTION = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int PARAMETERS = 22;
  /** RegularExpression Id. */
  int PROCEDURE = 23;
  /** RegularExpression Id. */
  int RETURNS = 24;
  /** RegularExpression Id. */
  int PROGRAM = 25;
  /** RegularExpression Id. */
  int READ = 26;
  /** RegularExpression Id. */
  int REAL = 27;
  /** RegularExpression Id. */
  int RECORD = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int SET = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int THEN = 32;
  /** RegularExpression Id. */
  int TYPES = 33;
  /** RegularExpression Id. */
  int UNTIL = 34;
  /** RegularExpression Id. */
  int VAR = 35;
  /** RegularExpression Id. */
  int VARIABLES = 36;
  /** RegularExpression Id. */
  int WHILE = 37;
  /** RegularExpression Id. */
  int WRITE = 38;
  /** RegularExpression Id. */
  int BOOLEAN = 39;
  /** RegularExpression Id. */
  int TRUE = 40;
  /** RegularExpression Id. */
  int FALSE = 41;
  /** RegularExpression Id. */
  int DEFINE = 42;
  /** RegularExpression Id. */
  int OP_ADD = 43;
  /** RegularExpression Id. */
  int OP_SUB = 44;
  /** RegularExpression Id. */
  int OP_MULT = 45;
  /** RegularExpression Id. */
  int OP_DIV = 46;
  /** RegularExpression Id. */
  int OP_MOD = 47;
  /** RegularExpression Id. */
  int OP_EQUALS = 48;
  /** RegularExpression Id. */
  int OP_LESS = 49;
  /** RegularExpression Id. */
  int OP_GREATER = 50;
  /** RegularExpression Id. */
  int OP_LESS_OR_EQUAL = 51;
  /** RegularExpression Id. */
  int OP_GREATER_OR_EQUAL = 52;
  /** RegularExpression Id. */
  int OP_DIFFERENT = 53;
  /** RegularExpression Id. */
  int BRACKET_OPEN = 54;
  /** RegularExpression Id. */
  int BRACKET_CLOSE = 55;
  /** RegularExpression Id. */
  int PARETHESIS_OPEN = 56;
  /** RegularExpression Id. */
  int PARETHESIS_CLOSE = 57;
  /** RegularExpression Id. */
  int COMMA = 58;
  /** RegularExpression Id. */
  int DOT = 59;
  /** RegularExpression Id. */
  int SEMICOLON = 60;
  /** RegularExpression Id. */
  int AND = 61;
  /** RegularExpression Id. */
  int OR = 62;
  /** RegularExpression Id. */
  int NOT = 63;
  /** RegularExpression Id. */
  int INTEGER_CONST = 64;
  /** RegularExpression Id. */
  int REAL_CONST = 65;
  /** RegularExpression Id. */
  int DIGIT = 66;
  /** RegularExpression Id. */
  int IDENTIFIER = 67;
  /** RegularExpression Id. */
  int IDENTIFIER_ERR = 68;
  /** RegularExpression Id. */
  int STRING_START = 69;
  /** RegularExpression Id. */
  int STRING_CORE = 70;
  /** RegularExpression Id. */
  int STRING_CONST = 71;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT_LINE>",
    "\"{\"",
    "<COMMENT_BLOCK>",
    "<COMMENT_CORE>",
    "\"ARRAY\"",
    "\"BEGIN\"",
    "\"CALL\"",
    "\"DO\"",
    "\"ELSE\"",
    "\"END\"",
    "\"ENDIF\"",
    "\"ENDUNTIL\"",
    "\"ENDWHILE\"",
    "\"FUNCTION\"",
    "\"IF\"",
    "\"INTEGER\"",
    "\"PARAMETERS\"",
    "\"PROCEDURE\"",
    "\"RETURNS\"",
    "\"PROGRAM\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"RETURN\"",
    "\"SET\"",
    "\"STRING\"",
    "\"THEN\"",
    "\"TYPES\"",
    "\"UNTIL\"",
    "\"VAR\"",
    "\"VARIABLES\"",
    "\"WHILE\"",
    "\"WRITE\"",
    "\"BOOLEAN\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"DEFINE\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"&\"",
    "\"\\\\\"",
    "\"~\"",
    "<INTEGER_CONST>",
    "<REAL_CONST>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<IDENTIFIER_ERR>",
    "\"\\\"\"",
    "<STRING_CORE>",
    "<STRING_CONST>",
  };

}
