/* Generated By:JavaCC: Do not edit this line. JSONConstants.java */
package testJJ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JSONConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT_LINE = 6;
  /** RegularExpression Id. */
  int COMMENT_INNER = 7;
  /** RegularExpression Id. */
  int COMMENT_BLOCK = 8;
  /** RegularExpression Id. */
  int COMMENT_CORE = 9;
  /** RegularExpression Id. */
  int ARRAY = 10;
  /** RegularExpression Id. */
  int BEGIN = 11;
  /** RegularExpression Id. */
  int CALL = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int ENDIF = 16;
  /** RegularExpression Id. */
  int ENDUNTIL = 17;
  /** RegularExpression Id. */
  int ENDWHILE = 18;
  /** RegularExpression Id. */
  int FUNCTION = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int INTEGER = 21;
  /** RegularExpression Id. */
  int PARAMETERS = 22;
  /** RegularExpression Id. */
  int PROCEDURE = 23;
  /** RegularExpression Id. */
  int RETURNS = 24;
  /** RegularExpression Id. */
  int PROGRAM = 25;
  /** RegularExpression Id. */
  int READ = 26;
  /** RegularExpression Id. */
  int REAL = 27;
  /** RegularExpression Id. */
  int RECORD = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int SET = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int THEN = 32;
  /** RegularExpression Id. */
  int UNTIL = 33;
  /** RegularExpression Id. */
  int VAR = 34;
  /** RegularExpression Id. */
  int VARIABLES = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int WRITE = 37;
  /** RegularExpression Id. */
  int BOOLEAN = 38;
  /** RegularExpression Id. */
  int TRUE = 39;
  /** RegularExpression Id. */
  int FALSE = 40;
  /** RegularExpression Id. */
  int DEFINE = 41;
  /** RegularExpression Id. */
  int OP_ADD = 42;
  /** RegularExpression Id. */
  int OP_MULT = 43;
  /** RegularExpression Id. */
  int OP_REL = 44;
  /** RegularExpression Id. */
  int BRACKET_OPEN = 45;
  /** RegularExpression Id. */
  int BRACKET_CLOSE = 46;
  /** RegularExpression Id. */
  int PARETHESIS_OPEN = 47;
  /** RegularExpression Id. */
  int PARETHESIS_CLOSE = 48;
  /** RegularExpression Id. */
  int COMMA = 49;
  /** RegularExpression Id. */
  int DOT = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int AND = 52;
  /** RegularExpression Id. */
  int OR = 53;
  /** RegularExpression Id. */
  int NOT = 54;
  /** RegularExpression Id. */
  int INTEGER_CONST = 55;
  /** RegularExpression Id. */
  int REAL_CONST = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;
  /** RegularExpression Id. */
  int IDENTIFIER = 58;
  /** RegularExpression Id. */
  int IDENTIFIER_ERR = 59;
  /** RegularExpression Id. */
  int STRING_START = 60;
  /** RegularExpression Id. */
  int STRING_CORE = 61;
  /** RegularExpression Id. */
  int STRING_CONST = 62;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;
  /** Lexical state. */
  int IN_STRING = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMMENT_LINE>",
    "\"{\"",
    "<COMMENT_BLOCK>",
    "<COMMENT_CORE>",
    "\"ARRAY\"",
    "\"BEGIN\"",
    "\"CALL\"",
    "\"DO\"",
    "\"ELSE\"",
    "\"END\"",
    "\"ENDIF\"",
    "\"ENDUNTIL\"",
    "\"ENDWHILE\"",
    "\"FUNCTION\"",
    "\"IF\"",
    "\"INTEGER\"",
    "\"PARAMETERS\"",
    "\"PROCEDURE\"",
    "\"RETURNS\"",
    "\"PROGRAM\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"RETURN\"",
    "\"SET\"",
    "\"STRING\"",
    "\"THEN\"",
    "\"UNTIL\"",
    "\"VAR\"",
    "\"VARIABLES\"",
    "\"WHILE\"",
    "\"WRITE\"",
    "\"BOOLEAN\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"DEFINE\"",
    "<OP_ADD>",
    "<OP_MULT>",
    "<OP_REL>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\".\"",
    "\";\"",
    "\"&\"",
    "\"\\\\\"",
    "\"~\"",
    "<INTEGER_CONST>",
    "<REAL_CONST>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<IDENTIFIER_ERR>",
    "\"\\\"\"",
    "<STRING_CORE>",
    "<STRING_CONST>",
  };

}
